=== pranish1008/codeashop/cw.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="codeashop">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nav_bar">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="home"/>
              <xs:element type="xs:string" name="sign_up"/>
              <xs:element type="xs:string" name="register"/>
              <xs:element type="xs:string" name="login"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="title"/>
        <xs:element name="store">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="store_info" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="img"/>
                    <xs:element type="xs:string" name="Name"/>
                    <xs:element name="phone_info">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="landline_number" minOccurs="0"/>
                          <xs:element name="mobile_number" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="cell" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="email" minOccurs="0"/>
                    <xs:element type="xs:string" name="website" minOccurs="0"/>
                    <xs:element type="xs:string" name="location" minOccurs="0"/>
                    <xs:element type="xs:string" name="about_us" minOccurs="0"/>
                    <xs:element type="xs:string" name="logo" minOccurs="0"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="branch" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="gift_card">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="type" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="heading"/>
                    <xs:element name="steam_giftcard">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="cost" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="stimg"/>
                                <xs:element type="xs:string" name="giftcard_name"/>
                                <xs:element type="xs:string" name="description"/>
                                <xs:element type="xs:string" name="currency"/>
                                <xs:element type="xs:string" name="price"/>
                                <xs:element type="xs:string" name="type"/>
                                <xs:element type="xs:string" name="validity"/>
                                <xs:element type="xs:string" name="inventory" minOccurs="0"/>
                                <xs:element type="xs:string" name="delivery" minOccurs="0"/>
                                <xs:element type="xs:string" name="valid_in" minOccurs="0"/>
                              </xs:sequence>
                              <xs:attribute type="xs:byte" name="price" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="itunes_giftcard">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="itimg" minOccurs="0"/>
                          <xs:element name="cost" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="itimg"/>
                                <xs:element type="xs:string" name="giftcard_name"/>
                                <xs:element type="xs:string" name="description"/>
                                <xs:element type="xs:string" name="currency"/>
                                <xs:element type="xs:string" name="price"/>
                                <xs:element type="xs:string" name="type"/>
                                <xs:element type="xs:string" name="validity"/>
                                <xs:element type="xs:string" name="inventory" minOccurs="0"/>
                                <xs:element type="xs:string" name="delivery" minOccurs="0"/>
                                <xs:element type="xs:string" name="valid_in" minOccurs="0"/>
                              </xs:sequence>
                              <xs:attribute type="xs:byte" name="price" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="form" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="social">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="footer" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="conn" minOccurs="0"/>
                    <xs:element type="xs:string" name="fbimg" minOccurs="0"/>
                    <xs:element type="xs:string" name="instaimg" minOccurs="0"/>
                    <xs:element name="payment" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="conn" minOccurs="0"/>
                          <xs:element type="xs:string" name="esimg" minOccurs="0"/>
                          <xs:element type="xs:string" name="khimg" minOccurs="0"/>
                          <xs:element type="xs:string" name="visaimg" minOccurs="0"/>
                          <xs:element type="xs:string" name="masterimg" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="mode" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:short" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pranish1008/codeashop/cw.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<?xml-stylesheet type="text/css" href="cw.css"?>
<codeashop xsi:noNamespaceSchemaLocation="cw.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <nav_bar>
            <home>Home</home>
            <sign_up>Sign up</sign_up>
            <register>Register</register>
            <login>Login</login>
        </nav_bar>
        <title>
    Welcome to codeashop
        </title>
        <store>
            <store_info branch="Head Office">
                <img/>
                <Name>Name:Codeashop</Name>
                <phone_info>
                    <landline_number>Landline:014312979</landline_number>
                </phone_info>
                <email>Email:pranishmndr01@gmail.com</email>
                <website>Website:www.CODEASHOP.com</website>
                <location>Location:London</location>
                <about_us>About us:Codashop is a Virtual Giftcard Marketplace, where consumers buy, sell, earn and redeem Gift Cards, providing you a secure, transparent and safe options with complete transaction records, every time.</about_us>
                <logo/>
            </store_info>
            <store_info branch="Branch office">
                <img/>
                <Name>Name:Codeashop Branch</Name>
                <phone_info>
                    <mobile_number cell="primary">Primary number:9861244270</mobile_number>
                    <mobile_number cell="secondary">Secondary number:9851004063</mobile_number>
                </phone_info>
            </store_info>
        </store>
        <gift_card>
            <type form="physical">
                <heading>Physical Gift Cards</heading>
                <steam_giftcard>
                    <cost price="10">
                        <stimg/>
                        <giftcard_name>Name:10 &#36; Steam Gift Card</giftcard_name>
                        <description>Description:A Steam card is a gift card that can be redeemed through Steam for credit. Credit from Steam cards can be used to buy games.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:10</price>
                        <type>type:Physical</type>
                        <validity>Validity:1 year</validity>
                        <inventory>Stock:5</inventory>
                        <delivery>Delivery:Can be delivered all over UK only</delivery>
                    </cost>
                    <cost price="20">
                        <stimg/>
                        <giftcard_name>Name:20 &#36; Steam Gift Card</giftcard_name>
                        <description>Description:A Steam card is a gift card that can be redeemed through Steam for credit. Credit from Steam cards can be used to buy games.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:20</price>
                        <type>type:Physical</type>
                        <validity>Validity:1 year</validity>
                        <inventory>Stock:2</inventory>
                        <delivery>Delivery:Can be delivered all over UK only</delivery>
                    </cost>
                    <cost price="30">
                        <stimg/>
                        <giftcard_name>Name:30 &#36; Steam Gift Card</giftcard_name>
                        <description>Description:A Steam card is a gift card that can be redeemed through Steam for credit. Credit from Steam cards can be used to buy games.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:10</price>
                        <type>type:Physical</type>
                        <validity>Validity:1 year</validity>
                        <inventory>Stock:1</inventory>
                        <delivery>Delivery:Can be delivered all over UK only</delivery>
                    </cost>
                    <cost price="40">
                        <stimg/>
                        <giftcard_name>Name:40 &#36; Steam Gift Card</giftcard_name>
                        <description>Description:A Steam card is a gift card that can be redeemed through Steam for credit. Credit from Steam cards can be used to buy games.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:40</price>
                        <type>type:Physical</type>
                        <validity>Validity:1 year</validity>
                        <inventory>Stock:8</inventory>
                        <delivery>Delivery:Can be delivered all over UK only</delivery>
                    </cost>
                </steam_giftcard>
                <itunes_giftcard>
                    <itimg/>
                    <cost price="10">
                        <itimg/>
                        <giftcard_name>Name:10 &#36; Itunes Gift Card</giftcard_name>
                        <description>Description:A Itunes card is a gift card that can be redeemed through apple store for credit. Credit from Itunes cards can be used to buy music.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:10</price>
                        <type>type:Physical</type>
                        <validity>Validity:1 year</validity>
                        <inventory>Stock:4</inventory>
                        <delivery>Delivery:Can be delivered all over UK only</delivery>
                    </cost>
                    <cost price="20">
                        <itimg/>
                        <giftcard_name>Name:20 &#36; Itunes Gift Card</giftcard_name>
                        <description>Description:A Itunes card is a gift card that can be redeemed through apple store for credit. Credit from Itunes cards can be used to buy music.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:20</price>
                        <type>type:Physical</type>
                        <validity>Validity:1 year</validity>
                        <inventory>Stock:7</inventory>
                        <delivery>Delivery:Can be delivered all over UK only</delivery>
                    </cost>
                    <cost price="30">
                        <itimg/>
                        <giftcard_name>Name:30 &#36; Itunes Gift Card</giftcard_name>
                        <description>Description:A Itunes card is a gift card that can be redeemed through apple store for credit. Credit from Itunes cards can be used to buy music.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:30</price>
                        <type>type:Physical</type>
                        <validity>Validity:1 year</validity>
                        <inventory>Stock:8</inventory>
                        <delivery>Delivery:Can be delivered all over UK only</delivery>
                    </cost>
                    <cost price="40">
                        <itimg/>
                        <giftcard_name>Name:40 &#36; Itunes Gift Card</giftcard_name>
                        <description>Description:A Itunes card is a gift card that can be redeemed through apple store for credit. Credit from Itunes cards can be used to buy music.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:40</price>
                        <type>type:Physical</type>
                        <validity>Validity:1 year</validity>
                        <inventory>Stock:5</inventory>
                        <delivery>Delivery:Can be delivered all over UK only</delivery>
                    </cost>
                </itunes_giftcard>
            </type>
            <type form="digital">
                <heading>Digital Gift Cards</heading>
                <steam_giftcard>
                    <cost price="10">
                        <stimg/>
                        <giftcard_name>Name:10 &#36; Steam Gift Card</giftcard_name>
                        <description>Description:A Steam card is a gift card that can be redeemed through Steam for credit. Credit from Steam cards can be used to buy games.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:10</price>
                        <type>type:Digital</type>
                        <validity>Validity:1 year</validity>
                        <valid_in>Valid In:In UK and Wales  only</valid_in>
                    </cost>
                    <cost price="20">
                        <stimg/>
                        <giftcard_name>Name:20 &#36; Steam Gift Card</giftcard_name>
                        <description>Description:A Steam card is a gift card that can be redeemed through Steam for credit. Credit from Steam cards can be used to buy games.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:20</price>
                        <type>type:Digital</type>
                        <validity>Validity:1 year</validity>
                        <valid_in>Valid In:In UK and Wales  only</valid_in>
                    </cost>
                    <cost price="30">
                        <stimg/>
                        <giftcard_name>Name:30 &#36; Steam Gift Card</giftcard_name>
                        <description>Description:A Steam card is a gift card that can be redeemed through Steam for credit. Credit from Steam cards can be used to buy games.</description>
                        <currency>Currency:Dollars</currency>
                        <price>Price:30</price>
                        <type>type:Digital</type>
